### ISSUE TITLE
[ZAP-101] 체크한 조건 바탕으로 검색 결과 요청

### ISSUE THREAD

**Issue by SEOKJUN-KO** [marvelize/zapass_iOS#14]
## 💡  Feature Issue

체크한 조건 바탕으로 티켓 받아보기 버튼 클릭

- 이미 로그인 한 경우
검색 요청을 보내고, 로딩 뷰를 띄운다.

- 로그인이 필요한 경우
이름과 이메일 정보를 입력 후, 인증링크 보내기
인증이 완료 된 경우, 로그인 처리 후 
검색 요청을 보내고, 로딩 뷰를 띄운다.

| 이슈 내용 | 입력해주세요 |
| :--- | :--- |
| 마감 기한 | 2023.10.15 |

## ✅ To-do

- [ ] 로그인 여부 체크
- [ ] 조건에 맞는 검색 요청 보내기
- [ ] 로딩 뷰로 넘어가기
