### ISSUE TITLE
[ZAP-136] 챙기기 뷰 그리기

### ISSUE THREAD

**Issue by SEOKJUN-KO** [marvelize/zapass_iOS#23]
## 💡  Feature Issue

챙기기 뷰 그리기

| 이슈 내용 | 뷰 그리기 |
| :--- | :--- |
| 마감 기한 | 2023.10.23 |

## ✅ To-do

- [x] 입국 / 세관 , 티켓 컨테이너 컴포넌트화
- [x] 컨테이너 열린 것 컴포넌트 화
- [x] 컴포넌트 활용하여 뷰 그리기
- [x]  가이드 뷰 그리기
