### ISSUE TITLE
[ZAP-143] 챙기기 리팩토링 1차

### ISSUE THREAD

**Issue by SEOKJUN-KO** [marvelize/zapass_iOS#36]
## 💡  Feature Issue

| 이슈 내용 | 리팩토링 |
| :--- | :--- |
| 마감 기한 | 2023.10.24 |

## ✅ To-do

- [x] 입국, 세관 QR 선택 다시 할 수 있게 하기
- [x] 입국, 세관 QR 수정, 삭제 할 수 있게 하기
- [x] QR 사진 편집 뷰 이전으로 돌아가고, 다시 QR 사진 편집으로 돌아올 때 사진 변경하지 않아도 돌아올 수 있게 하기
- [x] 앱 틴트 컬러 바꾸기
