### ISSUE TITLE
[ZAP-147] 챙기기 - 입국, 세관, 면세 QR 관련 기능

### ISSUE THREAD

**Issue by SEOKJUN-KO** [marvelize/zapass_iOS#67]
## 💡  Feature Issue

달력 구현 이외의, 입국/세관/면세에 관련한 기능과 뷰

| 이슈 내용 | 입국/세관/면세 |
| :--- | :--- |
| 마감 기한 | 2023.11.5 |

## ✅ To-do

- [x] 입국/세관/면세 선택
- [x] qr 이미지 보라색 선 나오는거 수정
- [x] 선택된 것 보라색 테두리
- [x] 오른쪽 x 클릭시, 이미지 삭제
