### ISSUE TITLE
[ZAP-148] 챙기기 - 기타 저장하기 기능 추가

### ISSUE THREAD

**Issue by SEOKJUN-KO** [marvelize/zapass_iOS#72]
## 💡  Feature Issue

- 기타 QR 정보를 저장하는 전체 플로우를 개발

| 이슈 내용 | 기타 QR 등록 |
| :--- | :--- |
| 마감 기한 | 2023.11.10 |

## ✅ To-do

- [ ] 패스 이름 입력 받기
- [ ] 패스 사용기간 입력 받기
- [ ] 사진 입력 받기
- [ ] 사진과 패스 이름, 패스 사용기간 연결하기
- [ ] 저장하기
